spring.application.name=fake-restaurant-BE

application.title=Fake Restaurant

#server.servlet.context-path=/myprefix

server.port=8080
spring.threads.virtual.enabled=false

spring.jackson.serialization.write-dates-as-timestamps=false
server.http2.enabled=true

# We disable transaction without specific handling (we are designing mostly a REST API).
# Please avoid to enable it before serious specific reasons since it severely may affect performances.
spring.jpa.open-in-view=false

fake-restaurant.config.secret-jwt-key=${jwt.secret}



# https://docs.spring.io/spring-boot/docs/1.3.0.M1/reference/html/production-ready-endpoints.html#:~:text=Actuator%20endpoints%20allow%20you%20to,provides%20basic%20application%20health%20information.
management.endpoints.web.exposure.include=health,prometheus
management.server.port=8911
management.server.address=127.0.0.1
management.endpoint.prometheus.access=read_only

server.forward-headers-strategy=native
spring.profiles.active=security-enable

#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=validate
#spring.datasource.url=jdbc:mysql://localhost:3306/tuo_db
#spring.datasource.username=root
#spring.datasource.password=pass
#spring.jpa.show-sql=true



