openapi: 3.0.3
info:
  title: Server
  version: '1'
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Managing API
  - name: Public API
    description: Backend functions for public endpoints
  - name: User API
    description: Backend functions for user endpoints
paths:
  /public/login:
    post:
      tags:
        - Public API
      operationId: LoginPost
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Token JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

  /public/register:
    post:
      tags:
        - Public API
      operationId: RegisterPost
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Token JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - User API
      operationId: UsersPost
      summary: Bootstrap user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: the user uuid
          content:
            application/json:
              schema:
                type: string
                format: uuid
        401:
          $ref: '#/components/responses/Unauthorized_401'
    get:
      tags:
        - User API
      parameters:
        - $ref: '#/components/parameters/PageQueryParam'
        - $ref: '#/components/parameters/SizeQueryParam'
        - $ref: '#/components/parameters/SearchQueryParam'
      operationId: UsersGet
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                title: UsersPage
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                  page:
                    $ref: "#/components/schemas/Page"
        401:
          $ref: '#/components/responses/Unauthorized_401'
  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/UUIDParamPath'
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - User API
      operationId: UserIdGet
      summary: Get User Data
      responses:
        200:
          description: the user uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized_401'
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - User API
      operationId: UserIdPut
      summary: Modify User Data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: the user uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/Unauthorized_401'
        404:
          $ref: '#/components/responses/Not_Found_404'

components:
  responses:
    Unauthorized_401:
      description: Unauthorized_401
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Not_Found_404:
      description: Not_Found_404
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  parameters:
    PageQueryParam:
      in: query
      required: false
      name: page
      schema:
        type: integer
        format: int32
      description: |
        Page numbers starting at 0.
    SizeQueryParam:
      in: query
      required: false
      name: size
      schema:
        type: integer
        format: int32
      description: |
        Size 0 equals to default size. Maximum size may be limited anytime and not honored by the backend.

    SearchQueryParam:
      in: query
      required: false
      name: search
      schema:
        type: string
      description: |
        Search keyword to search in element.

    UUIDParamPath:
      in: path
      required: true
      name: id
      schema:
        type: string
        format: uuid



  schemas:
    Page:
      type: object
      properties:
        size:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64

    User:
      type: object
      required:
        - id
        - name
        - surname
        - email
        - role
      properties:
        id:
          $ref: "#/components/schemas/UUIDReference"
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        role:
          $ref: '#/components/schemas/Role'
        password:
          type: string
          format: password
        createdAt:
          $ref: '#/components/schemas/InstantDateTimeRO'
        updatedAt:
          $ref: '#/components/schemas/InstantDateTimeRO'

    Restaurant:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUIDReference"
        name:
          type: string
        description:
          type: string
        createdAt:
          $ref: '#/components/schemas/InstantDateTimeRO'
        latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
        thumbnail:
          type: string
        ownerUserId:
          $ref: "#/components/schemas/UUIDReference"
#        defaultLanguage:
#          type: string
#        disabledAt:
#          $ref: '#/components/schemas/InstantDateTimeRO'

    Review:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUIDReference"
        title:
          type: string
        description:
          type: string
        votes:
          type: array
          items:
            $ref: "#/components/schemas/Vote"
        createdAt:
          $ref: '#/components/schemas/InstantDateTimeRO'
        thumbnail:
          type: string
        restaurantId:
          $ref: "#/components/schemas/UUIDReference"
        ownerUserId:
          $ref: "#/components/schemas/UUIDReference"

    Vote:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUIDReference"
        voteType:
          $ref: "#/components/schemas/VoteType"
        createdAt:
          $ref: '#/components/schemas/InstantDateTimeRO'
        reviewId:
          $ref: "#/components/schemas/UUIDReference"
        ownerUserId:
          $ref: "#/components/schemas/UUIDReference"

    VoteType:
      type: string
      enum:
        - UP
        - DOWN

    Role:
      type: string
      enum:
        - ADMIN
        - USER

    InstantDateTime:
      type: object
      example: "2025-01-01T12:00:00.000Z"
      properties:
        foo:
          type: object

    InstantDateTimeRO:
      type: object
      readOnly: true
      example: "2025-01-01T12:00:00.000Z"
      properties:
        foo:
          type: object

    UUIDReference:
      type: string
      format: uuid
      readOnly: true

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    TokenResponse:
      type: object
      properties:
        token:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
